services:
  email-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: email-provisioning-api
    ports:
      - "8002:8000"
    environment:
      # DirectAdmin Configuration
      - DIRECTADMIN_HOST=${DIRECTADMIN_HOST}
      - DIRECTADMIN_USER=${DIRECTADMIN_USER}
      - DIRECTADMIN_KEY=${DIRECTADMIN_KEY}
      - DEFAULT_DOMAIN=${DEFAULT_DOMAIN}

      # Database
      - DATABASE_URL=sqlite:////app/data/email.db

      # JWT Authentication
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRE_MINUTES=${JWT_EXPIRE_MINUTES:-1440}

      # Default Admin User
      - DEFAULT_ADMIN_EMAIL=${DEFAULT_ADMIN_EMAIL}
      - DEFAULT_ADMIN_PASSWORD=${DEFAULT_ADMIN_PASSWORD}

      # SMTP Settings
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT:-587}
      - SMTP_USERNAME=${SMTP_USERNAME}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL}
      - SMTP_FROM_NAME=${SMTP_FROM_NAME:-Email Provisioning API}

      # URLs
      - API_BASE_URL=${API_BASE_URL:-https://admin.faso.dev}
      - WEBMAIL_URL=${WEBMAIL_URL:-https://webmail.xseller.io}

      # Password Reset
      - RESET_TOKEN_EXPIRY_HOURS=${RESET_TOKEN_EXPIRY_HOURS:-48}

    volumes:
      # Persist SQLite database
      - email-db:/app/data

    restart: unless-stopped

    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request; urllib.request.urlopen('http://localhost:8000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  email-db:
    name: email_provisioning_db
